## `Notes:`

* we can only represet 1D,2D and 3D array.
* To know dimentions of array we use `array.ndim`
* array.size gives the number of elements
* size gives the number of rows and columns
* to produce numbers in floating values is not possible from range() function so we use `np.arange()` to do so
* I can easily do arithmetic operations with arrays 
* slicing works like - `array[row_start:row_end,column]`
* to do matrix multipication we use @ like - `array1@array2`
* we cannot transpose single dimentional array 
* to convert a two dimentional array into one dimentional `array.flatten()` function is used
* to convert an one dimentional array into two dimentional array , `np.expand_dims` function is used
* In numpy for string there everything is available in `np.char.any_function` this function

In [1]:
import numpy as np

In [2]:
ar = [1,2,3,4,5]

### array
`Syntax` : np.array()

In [3]:
np.array(ar)

array([1, 2, 3, 4, 5])

In [4]:
np.array([ar,[6,7,8,4,5]])

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 4, 5]])

In [70]:
print(type(ar))
# now i wanna to convert ar to array
asarry = np.asanyarray(ar)
print(type(asarry))


<class 'list'>
<class 'numpy.ndarray'>


#### matrix is a subset of array

In [6]:
matrix =np.matrix(ar)
matrix
# matrix is by default is two dimentional

matrix([[1, 2, 3, 4, 5]])

In [7]:
# now I wanna to convert matrix to array
np.asanyarray(matrix)
# this have not converted to array because matrix is already is subset of array

matrix([[1, 2, 3, 4, 5]])

In [8]:
# to produce array we use some type of functions like....
def fromfunction(i,j):
    return i == j 
print(np.fromfunction(fromfunction,(3,3)))

def fromfunction1(i,j):
    return i+j
np.fromfunction(fromfunction1,(10,5),dtype=int)


[[ True False False]
 [False  True False]
 [False False  True]]


array([[ 0,  1,  2,  3,  4],
       [ 1,  2,  3,  4,  5],
       [ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10],
       [ 7,  8,  9, 10, 11],
       [ 8,  9, 10, 11, 12],
       [ 9, 10, 11, 12, 13]])

In [9]:
np.fromiter((i for i in range(5,10)),dtype=float)

array([5., 6., 7., 8., 9.])

In [10]:
np.fromstring('3,4,3,445,65,333,22, ',sep=',')

array([  3.,   4.,   3., 445.,  65., 333.,  22.,  -1.])

## Data types

In [11]:

# this is one dimentional
ls = [1,2,3,4,5]
arr = np.array(ls)

print(arr.ndim)
print(arr.size)
arr

1
5


array([1, 2, 3, 4, 5])

In [12]:
# this is two dimentional
ls2D = [[1,2,3,4,5],[1,2,3,4,5]]
arr2D = np.array(ls2D)
print(arr2D.ndim)
print(arr2D.size)
print(arr2D.shape)

arr2D

2
10
(2, 5)


array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

## to produce numbers in floating values is not possible from range() function so we use np.arange to do so


In [13]:
(np.arange(0.3,9.6))



array([0.3, 1.3, 2.3, 3.3, 4.3, 5.3, 6.3, 7.3, 8.3, 9.3])

In [14]:
# to jump 
np.arange(0.3,10.3,.4)

array([0.3, 0.7, 1.1, 1.5, 1.9, 2.3, 2.7, 3.1, 3.5, 3.9, 4.3, 4.7, 5.1,
       5.5, 5.9, 6.3, 6.7, 7.1, 7.5, 7.9, 8.3, 8.7, 9.1, 9.5, 9.9])

## linSpace function

In [15]:
np.linspace(1,20,100)

array([ 1.        ,  1.19191919,  1.38383838,  1.57575758,  1.76767677,
        1.95959596,  2.15151515,  2.34343434,  2.53535354,  2.72727273,
        2.91919192,  3.11111111,  3.3030303 ,  3.49494949,  3.68686869,
        3.87878788,  4.07070707,  4.26262626,  4.45454545,  4.64646465,
        4.83838384,  5.03030303,  5.22222222,  5.41414141,  5.60606061,
        5.7979798 ,  5.98989899,  6.18181818,  6.37373737,  6.56565657,
        6.75757576,  6.94949495,  7.14141414,  7.33333333,  7.52525253,
        7.71717172,  7.90909091,  8.1010101 ,  8.29292929,  8.48484848,
        8.67676768,  8.86868687,  9.06060606,  9.25252525,  9.44444444,
        9.63636364,  9.82828283, 10.02020202, 10.21212121, 10.4040404 ,
       10.5959596 , 10.78787879, 10.97979798, 11.17171717, 11.36363636,
       11.55555556, 11.74747475, 11.93939394, 12.13131313, 12.32323232,
       12.51515152, 12.70707071, 12.8989899 , 13.09090909, 13.28282828,
       13.47474747, 13.66666667, 13.85858586, 14.05050505, 14.24

## zeros function

In [16]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
zero= np.zeros((10,30))
print(zero.shape)
zero
# here are 10 rows and 30 columns

(10, 30)


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [18]:
zeros= np.zeros((3,3,4))
print(zero.shape)
print(zeros.ndim)
zeros
# here are 3 matrixs or arrays of 3 rows and 4 columns

(10, 30)
3


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## ones function

In [19]:
# one dimentional ones array or matrix
np.ones(4)


array([1., 1., 1., 1.])

In [20]:
# two dimentional ones array or matrix
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
# three dimentional ones array or matrix
np.ones((2,3,4))


array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [22]:
# I can easily do arithmetic operations with arrays 
np.ones((2,4,4))* 3 +32/2

array([[[19., 19., 19., 19.],
        [19., 19., 19., 19.],
        [19., 19., 19., 19.],
        [19., 19., 19., 19.]],

       [[19., 19., 19., 19.],
        [19., 19., 19., 19.],
        [19., 19., 19., 19.],
        [19., 19., 19., 19.]]])

empty function

In [23]:
np.empty((8,7))
# these are less values

array([[1.28578474e-311, 1.28575778e-311, 1.28580497e-311,
        1.28579252e-311, 1.28580497e-311, 1.28580518e-311,
        1.28580479e-311],
       [1.28580497e-311, 1.28580517e-311, 1.28580477e-311,
        1.28580519e-311, 1.28580497e-311, 1.28580514e-311,
        1.28580511e-311],
       [1.28580510e-311, 1.28580497e-311, 1.28580520e-311,
        1.28580497e-311, 1.28577633e-311, 1.28580497e-311,
        1.28580497e-311],
       [1.28580520e-311, 1.28580516e-311, 1.28580511e-311,
        1.28576133e-311, 1.28575987e-311, 1.28576384e-311,
        1.28576119e-311],
       [1.28579256e-311, 1.28575963e-311, 1.28580521e-311,
        1.28577988e-311, 6.95220969e-310, 1.28580521e-311,
        1.28580521e-311],
       [1.28580521e-311, 1.28580517e-311, 1.28580521e-311,
        1.28580521e-311, 1.28580521e-311, 1.28580521e-311,
        1.28579565e-311],
       [1.28580521e-311, 1.28580521e-311, 1.28579361e-311,
        1.28580521e-311, 1.28580521e-311, 1.28580521e-311,
        1.28580521

##  eye function

In [24]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## random function


In [25]:
np.random.randn(3,4)
# this randn functions mean is always 0 and `std` is always 1

array([[ 1.13604622, -0.65513995,  0.68230174,  0.68609361],
       [ 0.24318538,  0.98512554,  0.39078238,  0.1235026 ],
       [ 0.12567499, -0.63732252,  0.7730239 , -1.09492305]])

In [26]:
np.random.rand(2,3)
# this without anything produces the data

array([[0.74660331, 0.74148197, 0.27287948],
       [0.26275178, 0.13863257, 0.54079121]])

In [27]:
np.random.randint(1,20,size=20)

array([ 2,  8,  2, 16,  3,  4, 14, 10,  4,  9, 18, 19,  5, 14,  8, 10, 10,
        2,  2, 14])

In [28]:
arr_randint =np.random.randint(1,20,size=(10,20))


In [29]:
# reshaping my data
arr_randint.reshape(1,200)

array([[10, 15, 19,  3, 16, 18, 12,  5,  1, 19, 12, 19, 16,  4,  2,  4,
        15, 11,  2,  7, 16,  5,  6, 11,  8,  3, 15, 15, 17,  2, 15, 12,
         4,  2, 14,  5, 11,  1, 12, 11, 19, 15,  3,  2, 18,  3,  9,  9,
        14,  5, 16,  4,  1,  7,  7, 12,  3,  3,  4,  1, 16,  7,  3, 13,
         2, 10,  2,  3, 11, 18, 18, 19,  5, 11,  6, 19, 11, 17,  6, 19,
         5, 19, 17, 14,  5,  4, 15,  5,  8, 10, 11,  3,  5, 14, 19, 11,
        10,  4, 17,  4,  5, 12, 17, 18,  6,  7, 18,  1, 16, 16,  2,  1,
        16, 15, 13,  8, 14, 16, 18, 12,  4,  3,  7,  9, 12, 19,  9, 15,
         1, 18,  5,  3, 12, 17, 17, 13,  3, 11, 19, 12, 17, 11, 14, 17,
         8,  8,  6,  8, 10, 18, 17, 11, 15,  7, 14, 19,  9,  6,  4,  4,
        17,  6,  9,  2,  9, 14,  3, 18,  1, 12, 10, 11, 16, 18, 10, 16,
         6,  5, 12, 14, 19, 18,  7,  3,  7,  6,  8,  8,  5,  3,  5, 16,
         9, 13,  2, 10,  4, 15,  9, 11]])

In [30]:
arr1 = np.random.randint(1,100,size=(4,4))
arr1

array([[94, 93, 92, 91],
       [26, 57, 98, 52],
       [59, 37, 93, 80],
       [25, 86, 19, 94]])

## indexing and slicing
this works like - array[row_start:row_end,column]

In [31]:

# i wanna to get our 7 by indexing
print(arr1[0][3])
arr1

91


array([[94, 93, 92, 91],
       [26, 57, 98, 52],
       [59, 37, 93, 80],
       [25, 86, 19, 94]])

In [32]:
arr1[:,3]

array([91, 52, 80, 94])

In [33]:
# i wanna to get out 67, 63, 58 by indexing
arr1[1:,1]

array([57, 37, 86])

In [34]:
arr2 = np.random.randint(1,300,(5,6))
arr2

array([[ 44,  61, 218, 297, 189,  79],
       [246,   9,  59,   7, 120, 131],
       [ 99, 184,  43,  90, 235, 229],
       [282, 293, 189, 228, 244, 204],
       [ 20,  62,  86, 157,   1,  77]])

In [35]:
arr3 = arr2 > 200

In [36]:
arr3

array([[False, False,  True,  True, False, False],
       [ True, False, False, False, False, False],
       [False, False, False, False,  True,  True],
       [ True,  True, False,  True,  True,  True],
       [False, False, False, False, False, False]])

In [37]:
arr3[arr2 > 200]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [38]:
arr2[arr3]
# finnaly I brought data by my self which is greater than 200

array([218, 297, 246, 235, 229, 282, 293, 228, 244, 204])

In [39]:
# array for matrix multiplication
arr_mul1 = np.random.randint(1,4,(3,3))
arr_mul2 = np.random.randint(4,7,(3,4))

In [40]:
arr_mul1

array([[1, 1, 3],
       [1, 3, 2],
       [3, 3, 2]])

In [41]:
arr_mul2

array([[4, 6, 5, 4],
       [4, 4, 4, 6],
       [6, 4, 5, 4]])

In [42]:
arr_mul1 @ arr_mul2

array([[26, 22, 24, 22],
       [28, 26, 27, 30],
       [36, 38, 37, 38]])

## brodcasting
In this method we do any operations with complete row or column

In [43]:
arr_brodcast = np.random.randint(1,10,(4,4))


In [44]:
arr_brodcast

array([[5, 2, 4, 3],
       [5, 1, 1, 1],
       [1, 9, 2, 8],
       [3, 8, 4, 4]])

In [45]:
arr_to_add = np.array([1,2,3,4])

In [46]:
arr_to_add

array([1, 2, 3, 4])

In [47]:
arr_brodcast + arr_to_add

array([[ 6,  4,  7,  7],
       [ 6,  3,  4,  5],
       [ 2, 11,  5, 12],
       [ 4, 10,  7,  8]])

In [48]:
arr_to_add_col = np.array([[1,2,3,4]]).T
arr_to_add_col

array([[1],
       [2],
       [3],
       [4]])

In [49]:
arr_brodcast + arr_to_add_col

array([[ 6,  3,  5,  4],
       [ 7,  3,  3,  3],
       [ 4, 12,  5, 11],
       [ 7, 12,  8,  8]])

## other functions

In [50]:
arr_other= np.random.randint(1,10,(4,4))
arr_other


array([[8, 2, 5, 8],
       [8, 4, 3, 4],
       [5, 5, 4, 8],
       [2, 7, 7, 1]])

In [51]:
np.square(arr_other)

array([[64,  4, 25, 64],
       [64, 16,  9, 16],
       [25, 25, 16, 64],
       [ 4, 49, 49,  1]])

In [52]:
np.sqrt(arr_other)

array([[2.82842712, 1.41421356, 2.23606798, 2.82842712],
       [2.82842712, 2.        , 1.73205081, 2.        ],
       [2.23606798, 2.23606798, 2.        , 2.82842712],
       [1.41421356, 2.64575131, 2.64575131, 1.        ]])

In [53]:
np.exp2(arr_other)

array([[256.,   4.,  32., 256.],
       [256.,  16.,   8.,  16.],
       [ 32.,  32.,  16., 256.],
       [  4., 128., 128.,   2.]])

In [54]:
np.exp(arr_other)


array([[2.98095799e+03, 7.38905610e+00, 1.48413159e+02, 2.98095799e+03],
       [2.98095799e+03, 5.45981500e+01, 2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 1.48413159e+02, 5.45981500e+01, 2.98095799e+03],
       [7.38905610e+00, 1.09663316e+03, 1.09663316e+03, 2.71828183e+00]])

In [55]:
np.log2(arr_other)

array([[3.        , 1.        , 2.32192809, 3.        ],
       [3.        , 2.        , 1.5849625 , 2.        ],
       [2.32192809, 2.32192809, 2.        , 3.        ],
       [1.        , 2.80735492, 2.80735492, 0.        ]])

In [56]:
np.log10(arr_other)

array([[0.90308999, 0.30103   , 0.69897   , 0.90308999],
       [0.90308999, 0.60205999, 0.47712125, 0.60205999],
       [0.69897   , 0.69897   , 0.60205999, 0.90308999],
       [0.30103   , 0.84509804, 0.84509804, 0.        ]])

## Array manipulation

In [59]:
array = np.random.randint(1,10,(3,4))
array

array([[6, 8, 7, 8],
       [6, 2, 1, 5],
       [2, 1, 1, 4]])

In [77]:
# changing number of rows and columns - I can only reshape this of multiplication of 12

print(array.reshape(2,6))

print('anotheer array : ',array.reshape(1,12))
print('anotheer array2 : ',array.reshape(12,1))
print('anotheer array3 : ',array.reshape(4,3))
print('anotheer array4 : ',array.reshape(4,3))


[[6 8 7 8 6 2]
 [1 5 2 1 1 4]]
anotheer array :  [[6 8 7 8 6 2 1 5 2 1 1 4]]
anotheer array2 :  [[6]
 [8]
 [7]
 [8]
 [6]
 [2]
 [1]
 [5]
 [2]
 [1]
 [1]
 [4]]
anotheer array3 :  [[6 8 7]
 [8 6 2]
 [1 5 2]
 [1 1 4]]
anotheer array4 :  [[6 8 7]
 [8 6 2]
 [1 5 2]
 [1 1 4]]


## flatten function

In [78]:
array.flatten()

array([6, 8, 7, 8, 6, 2, 1, 5, 2, 1, 1, 4])

## expand_dims function

In [82]:
arr_expandDim = np.random.randint(1,10,20)
arr_expandDim

array([8, 8, 7, 2, 8, 1, 2, 6, 6, 5, 6, 6, 7, 4, 4, 8, 8, 7, 9, 6])

In [85]:
np.expand_dims(arr_expandDim, axis=0)

array([[8, 8, 7, 2, 8, 1, 2, 6, 6, 5, 6, 6, 7, 4, 4, 8, 8, 7, 9, 6]])

In [88]:
np.expand_dims(arr_expandDim, axis=1)

array([[8],
       [8],
       [7],
       [2],
       [8],
       [1],
       [2],
       [6],
       [6],
       [5],
       [6],
       [6],
       [7],
       [4],
       [4],
       [8],
       [8],
       [7],
       [9],
       [6]])

## repeat function
this repeats each element as the value we give

In [93]:
arr_repeat = np.random.randint(1,10,5)
arr_repeat


array([6, 8, 8, 1, 8])

In [95]:
np.repeat(arr_repeat,4)

array([6, 6, 6, 6, 8, 8, 8, 8, 8, 8, 8, 8, 1, 1, 1, 1, 8, 8, 8, 8])

## roll function
this rolls the array as the value we give to shift

In [100]:
arr_roll = np.random.randint(1,10,6)
arr_roll

array([5, 3, 4, 1, 7, 1])

In [103]:
np.roll(a=arr_roll,shift=2)

array([7, 1, 5, 3, 4, 1])

## diag function
In this we gives a single dimentional array and this make 2D array and that arrays value assign to dialgonal

In [106]:
arr_diag = np.random.randint(1,10,6)
arr_diag


array([8, 2, 2, 7, 4, 4])

In [107]:
np.diag(arr_diag)


array([[8, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 4]])

## String Functions


In [112]:
arr_str = np.array([['gyan','prakash','kushwaha']])
arr_str

array([['gyan', 'prakash', 'kushwaha']], dtype='<U8')

In [115]:
np.char.encode(arr_str)

array([[b'gyan', b'prakash', b'kushwaha']], dtype='|S8')

In [123]:
end=np.char.endswith(arr_str,'gyan')
arr_str[end]

array(['gyan'], dtype='<U8')

In [125]:
np.char.upper(arr_str)

array([['GYAN', 'PRAKASH', 'KUSHWAHA']], dtype='<U8')

In [126]:
np.char.capitalize(arr_str)

array([['Gyan', 'Prakash', 'Kushwaha']], dtype='<U8')

## Mathematical functions

In [129]:
arr_maths = np.random.randint(1,10,(3,3))
arr_maths


array([[2, 4, 2],
       [7, 7, 2],
       [8, 6, 1]])

In [131]:
np.sin(arr_maths)

array([[ 0.90929743, -0.7568025 ,  0.90929743],
       [ 0.6569866 ,  0.6569866 ,  0.90929743],
       [ 0.98935825, -0.2794155 ,  0.84147098]])

In [132]:
np.cos(arr_maths)

array([[-0.41614684, -0.65364362, -0.41614684],
       [ 0.75390225,  0.75390225, -0.41614684],
       [-0.14550003,  0.96017029,  0.54030231]])

In [138]:
np.power(arr_maths,2)

array([[ 4, 16,  4],
       [49, 49,  4],
       [64, 36,  1]], dtype=int32)

In [140]:
np.mean(arr_maths)

4.333333333333333

In [144]:
np.median(arr_maths
          )

4.0

In [145]:
np.var(arr_maths)

6.444444444444444

In [147]:
np.std(arr_maths)

2.5385910352879693

In [149]:
np.min(arr_maths)

1

In [150]:
np.max(arr_maths)

8

## sort, search and count function

In [153]:
arr_sort_search_count = np.array(np.random.randint(1,20,12))
arr_sort_search_count

array([ 5,  2,  9, 16,  8,  3,  5, 18, 13, 10, 17,  9])

In [155]:
np.sort(arr_sort_search_count)


array([ 2,  3,  5,  5,  8,  9,  9, 10, 13, 16, 17, 18])

In [159]:
arr_sort_search_count.shape

(12,)

In [161]:
np.searchsorted(arr_sort_search_count,3444)
#because I have 12 elements and these are in 0-11 index thats why this has given me the index of 12

12

### count nonzero fuction
this counts how many non zero values are in my data

In [171]:
arr_countNonZero = np.array([1,2,343,0,6,0,0,0,3434,0,767])
arr_countNonZero

array([   1,    2,  343,    0,    6,    0,    0,    0, 3434,    0,  767])

In [172]:
np.count_nonzero(arr_countNonZero)

6

### where function
this function returns value with position(index)

In [174]:
arr_where = np.array([1,2,343,0,6,0,0,0,3434,0,767])
np.where(arr_where== 0)


(array([3, 5, 6, 7, 9], dtype=int64),)

### extract function
this extracts Or take out as per given condition

In [178]:
arr_extract = np.array([1,2,343,0,6,0,0,0,3434,0,767])
np.extract(arr_extract>0,arr_extract)

array([   1,    2,  343,    6, 3434,  767])

## matrix library

In [179]:
import numpy.matlib as npm

In [181]:
npm.zeros(7)

matrix([[0., 0., 0., 0., 0., 0., 0.]])

In [183]:
npm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [185]:
npm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

## Linear Algebra

In [190]:
linear_arr1 =np.random.randint(2,10,(2,2))
linear_arr2 =np.random.randint(2,10,(2,2))
linear_arr1

array([[7, 3],
       [2, 6]])

In [192]:
linear_arr2

array([[6, 8],
       [7, 8]])

In [199]:
np.dot(linear_arr1,linear_arr2)

array([[63, 80],
       [54, 64]])