# Integer Encoding

In [32]:
import numpy as np

from keras.preprocessing.text import Tokenizer # this is for tokenizing like -> "I"- 1 ,"love"- 2 ,"deep"- 3 ,"learning"- 4
from keras.utils import pad_sequences # Since I have different sequences in sequence so that we use padding. if we use padding we actually give 0 values for sequence which have less counts


In [18]:
texts = ['go india',
		'india india',
		'hip hip hurray',
		'jeetega bhai jeetega india jeetega',
		'bharat mata ki jai',
		'kohli kohli',
		'sachin sachin',
		'dhoni dhoni',
		'modi ji ki jai',
		'inquilab zindabad']

In [17]:
tokenizer = Tokenizer(oov_token='GyanPrakash'   # this oov_token is for when my model will get an text which he have not seen in training than this will replace text with oov_token
                      ) 
tokenizer

In [19]:

tokenizer.fit_on_texts(texts=texts) 

In [20]:
# this is for unique words and which index is tokenizer is assigning.
tokenizer.word_index

{'GyanPrakash': 1,
 'india': 2,
 'jeetega': 3,
 'hip': 4,
 'ki': 5,
 'jai': 6,
 'kohli': 7,
 'sachin': 8,
 'dhoni': 9,
 'go': 10,
 'hurray': 11,
 'bhai': 12,
 'bharat': 13,
 'mata': 14,
 'modi': 15,
 'ji': 16,
 'inquilab': 17,
 'zindabad': 18}

In [23]:
# this shows frequency of the word
tokenizer.word_counts

OrderedDict([('go', 1),
             ('india', 4),
             ('hip', 2),
             ('hurray', 1),
             ('jeetega', 3),
             ('bhai', 1),
             ('bharat', 1),
             ('mata', 1),
             ('ki', 2),
             ('jai', 2),
             ('kohli', 2),
             ('sachin', 2),
             ('dhoni', 2),
             ('modi', 1),
             ('ji', 1),
             ('inquilab', 1),
             ('zindabad', 1)])

In [28]:
# This is used for sentence count
tokenizer.document_count

10

In [31]:
# this is to make the words in sequence
sequences = tokenizer.texts_to_sequences(texts=texts)
sequences , tokenizer.word_index

([[10, 2],
  [2, 2],
  [4, 4, 11],
  [3, 12, 3, 2, 3],
  [13, 14, 5, 6],
  [7, 7],
  [8, 8],
  [9, 9],
  [15, 16, 5, 6],
  [17, 18]],
 {'GyanPrakash': 1,
  'india': 2,
  'jeetega': 3,
  'hip': 4,
  'ki': 5,
  'jai': 6,
  'kohli': 7,
  'sachin': 8,
  'dhoni': 9,
  'go': 10,
  'hurray': 11,
  'bhai': 12,
  'bharat': 13,
  'mata': 14,
  'modi': 15,
  'ji': 16,
  'inquilab': 17,
  'zindabad': 18})

In [36]:
sequences = pad_sequences(sequences=sequences,padding='post')
print(sequences)
print('Now my data is ready for training')

[[10  2  0  0  0]
 [ 2  2  0  0  0]
 [ 4  4 11  0  0]
 [ 3 12  3  2  3]
 [13 14  5  6  0]
 [ 7  7  0  0  0]
 [ 8  8  0  0  0]
 [ 9  9  0  0  0]
 [15 16  5  6  0]
 [17 18  0  0  0]]
Now my data is ready for training
