# Ada, Gredient and XgBoost

In [52]:
from sklearn.datasets import make_classification
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.ensemble import AdaBoostClassifier , GradientBoostingClassifier
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, confusion_matrix , classification_report


In [30]:
X, y = make_classification(n_samples=1000, n_features=4,
                           n_informative=2, n_redundant=0,
                          random_state=0, shuffle=False)
X.shape
X

array([[-1.66853167, -1.29901346,  0.2746472 , -0.60362044],
       [-2.9728827 , -1.08878294,  0.70885958,  0.42281857],
       [-0.59614125, -1.37007001, -3.11685659,  0.64445203],
       ...,
       [ 0.91711204,  1.10596645,  0.86766522, -2.25625012],
       [ 0.10027664,  1.45875846, -0.44360274, -0.67002328],
       [ 1.0415229 , -0.01987143,  0.15216419, -1.9405334 ]])

In [34]:
X_train, X_test, y_train, y_test = train_test_split(
     X, y, test_size=0.33, random_state=42)

In [64]:
ada_clf = AdaBoostClassifier()
grdb_clf = GradientBoostingClassifier()
xgb_clf = XGBClassifier()
xgb_clf

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=None, ...)

In [63]:
for clf in (ada_clf,grdb_clf,xgb_clf):
    clf.fit(X_train,y_train)
    y_pred = clf.predict(X_test)
    print(clf.__class__.__name__)
    print(f'accuracy score {round(accuracy_score(y_test,y_pred),ndigits=3)}')
    # print('')
    print(f'confusion_matrix \n {confusion_matrix(y_test,y_pred)}')
    # print('')
    print(f'classification_report \n {classification_report(y_test,y_pred)}')
    print('=============='*3)

AdaBoostClassifier
accuracy score 0.924
confusion_matrix 
 [[153  13]
 [ 12 152]]
classification_report 
               precision    recall  f1-score   support

           0       0.93      0.92      0.92       166
           1       0.92      0.93      0.92       164

    accuracy                           0.92       330
   macro avg       0.92      0.92      0.92       330
weighted avg       0.92      0.92      0.92       330

GradientBoostingClassifier
accuracy score 0.939
confusion_matrix 
 [[153  13]
 [  7 157]]
classification_report 
               precision    recall  f1-score   support

           0       0.96      0.92      0.94       166
           1       0.92      0.96      0.94       164

    accuracy                           0.94       330
   macro avg       0.94      0.94      0.94       330
weighted avg       0.94      0.94      0.94       330

XGBClassifier
accuracy score 0.933
confusion_matrix 
 [[155  11]
 [ 11 153]]
classification_report 
               precision  