## `Notes:`

* we can only represet 1D,2D and 3D array.
* To know dimentions of array we use `array.ndim`
* array.size gives the number of elements
* size gives the number of rows and columns
* to produce numbers in floating values is not possible from range() function so we use `np.arange()` to do so
* I can easily do arithmetic operations with arrays 
* slicing works like - `array[row_start:row_end,column]`
* to do matrix multipication we use @ like - `array1@array2`
* we cannot transpose single dimentional array 
* to convert a two dimentional array into one dimentional `array.flatten()` function is used
* to convert an one dimentional array into two dimentional array , `np.expand_dims` function is used
* In numpy for string there everything is available in `np.char.any_function` this function

In [2]:
import numpy as np

In [3]:
ar = [1,2,3,4,5]

### array
`Syntax` : np.array()

In [4]:
np.array(ar)

array([1, 2, 3, 4, 5])

In [5]:
np.array([ar,[6,7,8,4,5]])

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 4, 5]])

In [6]:
print(type(ar))
# now i wanna to convert ar to array
asarry = np.asanyarray(ar)
print(type(asarry))


<class 'list'>
<class 'numpy.ndarray'>


#### matrix is a subset of array

In [7]:
matrix =np.matrix(ar)
matrix
# matrix is by default is two dimentional

matrix([[1, 2, 3, 4, 5]])

In [8]:
# now I wanna to convert matrix to array
np.asanyarray(matrix)
# this have not converted to array because matrix is already is subset of array

matrix([[1, 2, 3, 4, 5]])

In [9]:
# to produce array we use some type of functions like....
def fromfunction(i,j):
    return i == j 
print(np.fromfunction(fromfunction,(3,3)))

def fromfunction1(i,j):
    return i+j
np.fromfunction(fromfunction1,(10,5),dtype=int)


[[ True False False]
 [False  True False]
 [False False  True]]


array([[ 0,  1,  2,  3,  4],
       [ 1,  2,  3,  4,  5],
       [ 2,  3,  4,  5,  6],
       [ 3,  4,  5,  6,  7],
       [ 4,  5,  6,  7,  8],
       [ 5,  6,  7,  8,  9],
       [ 6,  7,  8,  9, 10],
       [ 7,  8,  9, 10, 11],
       [ 8,  9, 10, 11, 12],
       [ 9, 10, 11, 12, 13]])

In [10]:
np.fromiter((i for i in range(5,10)),dtype=float)

array([5., 6., 7., 8., 9.])

In [11]:
np.fromstring('3,4,3,445,65,333,22, ',sep=',')

array([  3.,   4.,   3., 445.,  65., 333.,  22.,  -1.])

## Data types

In [12]:

# this is one dimentional
ls = [1,2,3,4,5]
arr = np.array(ls)

print(arr.ndim)
print(arr.size)
arr

1
5


array([1, 2, 3, 4, 5])

In [13]:
# this is two dimentional
ls2D = [[1,2,3,4,5],[1,2,3,4,5]]
arr2D = np.array(ls2D)
print(arr2D.ndim)
print(arr2D.size)
print(arr2D.shape)

arr2D

2
10
(2, 5)


array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

## to produce numbers in floating values is not possible from range() function so we use np.arange to do so


In [14]:
(np.arange(0.3,9.6))



array([0.3, 1.3, 2.3, 3.3, 4.3, 5.3, 6.3, 7.3, 8.3, 9.3])

In [15]:
# to jump 
np.arange(0.3,10.3,.4)

array([0.3, 0.7, 1.1, 1.5, 1.9, 2.3, 2.7, 3.1, 3.5, 3.9, 4.3, 4.7, 5.1,
       5.5, 5.9, 6.3, 6.7, 7.1, 7.5, 7.9, 8.3, 8.7, 9.1, 9.5, 9.9])

## linSpace function

In [16]:
np.linspace(1,20,100)

array([ 1.        ,  1.19191919,  1.38383838,  1.57575758,  1.76767677,
        1.95959596,  2.15151515,  2.34343434,  2.53535354,  2.72727273,
        2.91919192,  3.11111111,  3.3030303 ,  3.49494949,  3.68686869,
        3.87878788,  4.07070707,  4.26262626,  4.45454545,  4.64646465,
        4.83838384,  5.03030303,  5.22222222,  5.41414141,  5.60606061,
        5.7979798 ,  5.98989899,  6.18181818,  6.37373737,  6.56565657,
        6.75757576,  6.94949495,  7.14141414,  7.33333333,  7.52525253,
        7.71717172,  7.90909091,  8.1010101 ,  8.29292929,  8.48484848,
        8.67676768,  8.86868687,  9.06060606,  9.25252525,  9.44444444,
        9.63636364,  9.82828283, 10.02020202, 10.21212121, 10.4040404 ,
       10.5959596 , 10.78787879, 10.97979798, 11.17171717, 11.36363636,
       11.55555556, 11.74747475, 11.93939394, 12.13131313, 12.32323232,
       12.51515152, 12.70707071, 12.8989899 , 13.09090909, 13.28282828,
       13.47474747, 13.66666667, 13.85858586, 14.05050505, 14.24

## zeros function

In [17]:
np.zeros(3)

array([0., 0., 0.])

In [18]:
zero= np.zeros((10,30))
print(zero.shape)
zero
# here are 10 rows and 30 columns

(10, 30)


array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [19]:
zeros= np.zeros((3,3,4))
print(zero.shape)
print(zeros.ndim)
zeros
# here are 3 matrixs or arrays of 3 rows and 4 columns

(10, 30)
3


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

## ones function

In [20]:
# one dimentional ones array or matrix
np.ones(4)


array([1., 1., 1., 1.])

In [21]:
# two dimentional ones array or matrix
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
# three dimentional ones array or matrix
np.ones((2,3,4))


array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [23]:
# I can easily do arithmetic operations with arrays 
np.ones((2,4,4))* 3 +32/2

array([[[19., 19., 19., 19.],
        [19., 19., 19., 19.],
        [19., 19., 19., 19.],
        [19., 19., 19., 19.]],

       [[19., 19., 19., 19.],
        [19., 19., 19., 19.],
        [19., 19., 19., 19.],
        [19., 19., 19., 19.]]])

empty function

In [24]:
np.empty((8,7))
# these are less values

array([[1.21029002e-311, 1.21026433e-311, 1.21036617e-311,
        1.21036617e-311, 1.21036617e-311, 1.21036617e-311,
        1.21036617e-311],
       [1.21036617e-311, 1.21036617e-311, 1.21036617e-311,
        1.21036617e-311, 1.21036617e-311, 1.21036617e-311,
        1.21036617e-311],
       [1.21036617e-311, 1.21036617e-311, 1.21036617e-311,
        1.21036617e-311, 1.21036617e-311, 1.21036617e-311,
        1.21036617e-311],
       [1.21036617e-311, 1.21036617e-311, 1.21036617e-311,
        1.21036617e-311, 1.21036617e-311, 1.21036617e-311,
        1.21036617e-311],
       [1.21036617e-311, 1.21036617e-311, 1.21036617e-311,
        1.21036617e-311, 1.21036617e-311, 1.21036617e-311,
        1.21036617e-311],
       [1.21036617e-311, 1.21036617e-311, 1.21036617e-311,
        1.21036617e-311, 1.21036617e-311, 1.21036617e-311,
        1.21036617e-311],
       [1.21036617e-311, 1.21036617e-311, 1.21036617e-311,
        1.21036617e-311, 1.21036617e-311, 1.21036617e-311,
        1.21036617

##  eye function

In [25]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## random function


In [26]:
np.random.randn(3,4)
# this randn functions mean is always 0 and `std` is always 1

array([[-0.45548691, -0.69188548,  0.07993574, -0.82835973],
       [ 1.89268231,  0.41632836,  0.85207691, -0.14745959],
       [ 0.2067691 ,  1.89049924, -0.68551993,  0.28341522]])

In [27]:
np.random.rand(2,3)
# this without anything produces the data

array([[0.04973296, 0.09767164, 0.59726168],
       [0.91012734, 0.42025928, 0.91033823]])

In [28]:
np.random.randint(1,20,size=20)

array([15, 12,  4, 13, 12, 10, 12,  6, 19, 11,  4,  1, 18,  9,  3, 19,  3,
       15, 16, 17])

In [29]:
arr_randint =np.random.randint(1,20,size=(10,20))


In [30]:
# reshaping my data
arr_randint.reshape(1,200)

array([[ 6, 10,  9, 17, 12, 15,  2,  6,  4,  4,  2, 10, 14, 10, 18, 16,
         2, 11, 18, 15,  9,  7,  2,  4,  4,  1,  3,  1, 11,  1,  2,  4,
        18,  5,  1,  1, 15, 17, 11, 15,  5,  7, 14, 16, 18, 14, 15, 17,
        10, 16, 18,  5,  8, 19,  1, 16,  3,  6,  7, 15,  4, 11,  5, 11,
         3, 13,  9, 10,  2, 14, 15,  9, 18, 15, 14,  4, 13, 14, 15, 19,
        15,  1, 17,  7,  4, 16,  4,  4, 13, 12, 19,  9,  5, 15,  8, 16,
         1,  9, 17,  3, 16,  2,  5,  6, 13,  9, 14, 14,  2, 12, 17,  7,
        13, 12,  1,  9, 11,  5,  1, 17,  3, 16, 15, 18,  2, 19,  7,  1,
        12, 10, 12,  9,  7,  2, 19,  2,  9, 15,  8, 17, 10, 13, 18, 19,
        13, 16, 18,  1, 19,  2, 14,  9,  1, 16,  3,  7,  7,  9, 14, 15,
        14,  7, 12,  5,  4, 18, 12, 18, 13,  2,  1,  3,  1, 15, 14,  6,
         7,  8, 14, 12, 18,  4, 18, 11,  2,  7, 17, 14,  1, 16, 13,  1,
         7, 16,  5,  2,  1,  1, 11,  4]])

In [21]:
np.random.randint(1000)

123

In [31]:
arr1 = np.random.randint(1,100,size=(4,4))
arr1

array([[99, 47, 24,  9],
       [57,  6, 60, 56],
       [45, 60, 44, 27],
       [87, 30, 37, 90]])

## indexing and slicing
this works like - array[row_start:row_end,column]

In [32]:

# i wanna to get our 7 by indexing
print(arr1[0][3])
arr1

9


array([[99, 47, 24,  9],
       [57,  6, 60, 56],
       [45, 60, 44, 27],
       [87, 30, 37, 90]])

In [33]:
arr1[:,3]

array([ 9, 56, 27, 90])

In [34]:
# i wanna to get out 67, 63, 58 by indexing
arr1[1:,1]

array([ 6, 60, 30])

In [35]:
arr2 = np.random.randint(1,300,(5,6))
arr2

array([[290, 198,  14, 262, 125, 240],
       [  2,  88, 223, 245,   6,  11],
       [ 89, 126,  96, 253, 141,  43],
       [134, 207, 240, 112, 127, 154],
       [282, 216, 237, 290, 209,  19]])

In [36]:
arr3 = arr2 > 200

In [37]:
arr3

array([[ True, False, False,  True, False,  True],
       [False, False,  True,  True, False, False],
       [False, False, False,  True, False, False],
       [False,  True,  True, False, False, False],
       [ True,  True,  True,  True,  True, False]])

In [38]:
arr3[arr2 > 200]

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True])

In [39]:
arr2[arr3]
# finnaly I brought data by my self which is greater than 200

array([290, 262, 240, 223, 245, 253, 207, 240, 282, 216, 237, 290, 209])

In [40]:
# array for matrix multiplication
arr_mul1 = np.random.randint(1,4,(3,3))
arr_mul2 = np.random.randint(4,7,(3,4))

In [41]:
arr_mul1

array([[3, 3, 2],
       [1, 3, 1],
       [2, 3, 3]])

In [42]:
arr_mul2

array([[5, 4, 6, 5],
       [5, 6, 4, 6],
       [4, 4, 5, 6]])

In [43]:
arr_mul1 @ arr_mul2

array([[38, 38, 40, 45],
       [24, 26, 23, 29],
       [37, 38, 39, 46]])

## brodcasting
In this method we do any operations with complete row or column

In [44]:
arr_brodcast = np.random.randint(1,10,(4,4))


In [45]:
arr_brodcast

array([[6, 6, 7, 7],
       [4, 3, 9, 6],
       [5, 7, 8, 6],
       [8, 5, 5, 8]])

In [46]:
arr_to_add = np.array([1,2,3,4])

In [47]:
arr_to_add

array([1, 2, 3, 4])

In [48]:
arr_brodcast + arr_to_add

array([[ 7,  8, 10, 11],
       [ 5,  5, 12, 10],
       [ 6,  9, 11, 10],
       [ 9,  7,  8, 12]])

In [49]:
arr_to_add_col = np.array([[1,2,3,4]]).T
arr_to_add_col

array([[1],
       [2],
       [3],
       [4]])

In [50]:
arr_brodcast + arr_to_add_col

array([[ 7,  7,  8,  8],
       [ 6,  5, 11,  8],
       [ 8, 10, 11,  9],
       [12,  9,  9, 12]])

## other functions

In [51]:
arr_other= np.random.randint(1,10,(4,4))
arr_other


array([[8, 2, 2, 3],
       [2, 6, 6, 2],
       [5, 1, 7, 1],
       [4, 6, 3, 1]])

In [52]:
np.square(arr_other)

array([[64,  4,  4,  9],
       [ 4, 36, 36,  4],
       [25,  1, 49,  1],
       [16, 36,  9,  1]])

In [53]:
np.sqrt(arr_other)

array([[2.82842712, 1.41421356, 1.41421356, 1.73205081],
       [1.41421356, 2.44948974, 2.44948974, 1.41421356],
       [2.23606798, 1.        , 2.64575131, 1.        ],
       [2.        , 2.44948974, 1.73205081, 1.        ]])

In [54]:
np.exp2(arr_other)

array([[256.,   4.,   4.,   8.],
       [  4.,  64.,  64.,   4.],
       [ 32.,   2., 128.,   2.],
       [ 16.,  64.,   8.,   2.]])

In [55]:
np.exp(arr_other)


array([[2.98095799e+03, 7.38905610e+00, 7.38905610e+00, 2.00855369e+01],
       [7.38905610e+00, 4.03428793e+02, 4.03428793e+02, 7.38905610e+00],
       [1.48413159e+02, 2.71828183e+00, 1.09663316e+03, 2.71828183e+00],
       [5.45981500e+01, 4.03428793e+02, 2.00855369e+01, 2.71828183e+00]])

In [56]:
np.log2(arr_other)

array([[3.        , 1.        , 1.        , 1.5849625 ],
       [1.        , 2.5849625 , 2.5849625 , 1.        ],
       [2.32192809, 0.        , 2.80735492, 0.        ],
       [2.        , 2.5849625 , 1.5849625 , 0.        ]])

In [57]:
np.log10(arr_other)

array([[0.90308999, 0.30103   , 0.30103   , 0.47712125],
       [0.30103   , 0.77815125, 0.77815125, 0.30103   ],
       [0.69897   , 0.        , 0.84509804, 0.        ],
       [0.60205999, 0.77815125, 0.47712125, 0.        ]])

## Array manipulation

In [58]:
array = np.random.randint(1,10,(3,4))
array

array([[5, 4, 4, 4],
       [6, 2, 4, 7],
       [2, 3, 7, 6]])

In [59]:
# changing number of rows and columns - I can only reshape this of multiplication of 12

print(array.reshape(2,6))

print('anotheer array : ',array.reshape(1,12))
print('anotheer array2 : ',array.reshape(12,1))
print('anotheer array3 : ',array.reshape(4,3))
print('anotheer array4 : ',array.reshape(4,3))


[[5 4 4 4 6 2]
 [4 7 2 3 7 6]]
anotheer array :  [[5 4 4 4 6 2 4 7 2 3 7 6]]
anotheer array2 :  [[5]
 [4]
 [4]
 [4]
 [6]
 [2]
 [4]
 [7]
 [2]
 [3]
 [7]
 [6]]
anotheer array3 :  [[5 4 4]
 [4 6 2]
 [4 7 2]
 [3 7 6]]
anotheer array4 :  [[5 4 4]
 [4 6 2]
 [4 7 2]
 [3 7 6]]


## flatten function

In [60]:
array.flatten()

array([5, 4, 4, 4, 6, 2, 4, 7, 2, 3, 7, 6])

## expand_dims function

In [61]:
arr_expandDim = np.random.randint(1,10,20)
arr_expandDim

array([1, 7, 5, 5, 5, 3, 7, 8, 4, 2, 7, 4, 4, 9, 1, 1, 9, 8, 9, 1])

In [62]:
np.expand_dims(arr_expandDim, axis=0)

array([[1, 7, 5, 5, 5, 3, 7, 8, 4, 2, 7, 4, 4, 9, 1, 1, 9, 8, 9, 1]])

In [63]:
np.expand_dims(arr_expandDim, axis=1)

array([[1],
       [7],
       [5],
       [5],
       [5],
       [3],
       [7],
       [8],
       [4],
       [2],
       [7],
       [4],
       [4],
       [9],
       [1],
       [1],
       [9],
       [8],
       [9],
       [1]])

## repeat function
this repeats each element as the value we give

In [64]:
arr_repeat = np.random.randint(1,10,5)
arr_repeat


array([8, 3, 8, 3, 3])

In [65]:
np.repeat(arr_repeat,4)

array([8, 8, 8, 8, 3, 3, 3, 3, 8, 8, 8, 8, 3, 3, 3, 3, 3, 3, 3, 3])

## roll function
this rolls the array as the value we give to shift

In [66]:
arr_roll = np.random.randint(1,10,6)
arr_roll

array([2, 1, 7, 4, 4, 8])

In [67]:
np.roll(a=arr_roll,shift=2)

array([4, 8, 2, 1, 7, 4])

## diag function
In this we gives a single dimentional array and this make 2D array and that arrays value assign to dialgonal

In [68]:
arr_diag = np.random.randint(1,10,6)
arr_diag


array([5, 4, 2, 7, 8, 6])

In [69]:
np.diag(arr_diag)


array([[5, 0, 0, 0, 0, 0],
       [0, 4, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 6]])

## String Functions


In [70]:
arr_str = np.array([['gyan','prakash','kushwaha']])
arr_str

array([['gyan', 'prakash', 'kushwaha']], dtype='<U8')

In [71]:
np.char.encode(arr_str)

array([[b'gyan', b'prakash', b'kushwaha']], dtype='|S8')

In [72]:
end=np.char.endswith(arr_str,'gyan')
arr_str[end]

array(['gyan'], dtype='<U8')

In [73]:
np.char.upper(arr_str)

array([['GYAN', 'PRAKASH', 'KUSHWAHA']], dtype='<U8')

In [74]:
np.char.capitalize(arr_str)

array([['Gyan', 'Prakash', 'Kushwaha']], dtype='<U8')

## Mathematical functions

In [75]:
arr_maths = np.random.randint(1,10,(3,3))
arr_maths


array([[1, 2, 6],
       [7, 2, 5],
       [2, 4, 7]])

In [76]:
np.sin(arr_maths)

array([[ 0.84147098,  0.90929743, -0.2794155 ],
       [ 0.6569866 ,  0.90929743, -0.95892427],
       [ 0.90929743, -0.7568025 ,  0.6569866 ]])

In [77]:
np.cos(arr_maths)

array([[ 0.54030231, -0.41614684,  0.96017029],
       [ 0.75390225, -0.41614684,  0.28366219],
       [-0.41614684, -0.65364362,  0.75390225]])

In [78]:
np.power(arr_maths,2)

array([[ 1,  4, 36],
       [49,  4, 25],
       [ 4, 16, 49]], dtype=int32)

In [79]:
np.mean(arr_maths)

4.0

In [80]:
np.median(arr_maths
          )

4.0

In [81]:
np.var(arr_maths)

4.888888888888889

In [82]:
np.std(arr_maths)

2.211083193570267

In [83]:
np.min(arr_maths)

1

In [84]:
np.max(arr_maths)

7

## sort, search and count function

In [85]:
arr_sort_search_count = np.array(np.random.randint(1,20,12))
arr_sort_search_count

array([ 7,  6,  9, 18, 18, 12, 10, 12,  8,  7, 15,  3])

In [86]:
np.sort(arr_sort_search_count)


array([ 3,  6,  7,  7,  8,  9, 10, 12, 12, 15, 18, 18])

In [87]:
arr_sort_search_count.shape

(12,)

In [88]:
np.searchsorted(arr_sort_search_count,3444)
#because I have 12 elements and these are in 0-11 index thats why this has given me the index of 12

12

### count nonzero fuction
this counts how many non zero values are in my data

In [89]:
arr_countNonZero = np.array([1,2,343,0,6,0,0,0,3434,0,767])
arr_countNonZero

array([   1,    2,  343,    0,    6,    0,    0,    0, 3434,    0,  767])

In [90]:
np.count_nonzero(arr_countNonZero)

6

### where function
this function returns value with position(index)

In [91]:
arr_where = np.array([1,2,343,0,6,0,0,0,3434,0,767])
np.where(arr_where== 0)


(array([3, 5, 6, 7, 9], dtype=int64),)

### extract function
this extracts Or take out as per given condition

In [92]:
arr_extract = np.array([1,2,343,0,6,0,0,0,3434,0,767])
np.extract(arr_extract>0,arr_extract)

array([   1,    2,  343,    6, 3434,  767])

## matrix library

In [93]:
import numpy.matlib as npm

In [94]:
npm.zeros(7)

matrix([[0., 0., 0., 0., 0., 0., 0.]])

In [95]:
npm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [96]:
npm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

## Linear Algebra

In [97]:
linear_arr1 =np.random.randint(2,10,(2,2))
linear_arr2 =np.random.randint(2,10,(2,2))
linear_arr1

array([[6, 8],
       [4, 5]])

In [98]:
linear_arr2

array([[8, 4],
       [8, 6]])

In [99]:
np.dot(linear_arr1,linear_arr2)

array([[112,  72],
       [ 72,  46]])

## np.c_

In [3]:
np.c_[np.array([1,2,3]), np.array([4,5,6])]

array([[1, 4],
       [2, 5],
       [3, 6]])